"""
static_loader.py — Static demo dataset for the Deal Sourcing Engine.
Used as graceful fallback when yfinance is unavailable or rate-limited.
All figures are illustrative / for demonstration purposes only.
"""

import pandas as pd
import numpy as np

# ─── STATIC COMPANY DATASET ──────────────────────────────────────────────────
STATIC_COMPANIES = [
    {
        "name": "Kering",
        "ticker": "KER.PA",
        "sector": "Luxury & Consumer",
        "mktcap_bn": 28.4,
        "ev_bn": 31.2,
        "revenue_mn": 17640,
        "ebitda_mn": 4120,
        "ebitda_margin_pct": 23.4,
        "revenue_growth_pct": -11.3,
        "net_debt_mn": 2800,
        "net_debt_ebitda": 0.68,
        "ev_ebitda": 7.6,
        "ev_revenue": 1.77,
        "pe_ntm": 14.2,
        "roe_pct": 18.4,
        "roic_pct": 11.2,
        "current_ratio": 1.32,
        "acq_score": 74,
        "country": "France",
    },
    {
        "name": "Atos",
        "ticker": "ATO.PA",
        "sector": "Technology & Media",
        "mktcap_bn": 0.4,
        "ev_bn": 3.1,
        "revenue_mn": 10630,
        "ebitda_mn": 412,
        "ebitda_margin_pct": 3.9,
        "revenue_growth_pct": -7.8,
        "net_debt_mn": 2700,
        "net_debt_ebitda": 6.55,
        "ev_ebitda": 7.5,
        "ev_revenue": 0.29,
        "pe_ntm": None,
        "roe_pct": -42.0,
        "roic_pct": -8.1,
        "current_ratio": 0.82,
        "acq_score": 38,
        "country": "France",
    },
    {
        "name": "Bouygues",
        "ticker": "EN.PA",
        "sector": "Industrials & Engineering",
        "mktcap_bn": 9.2,
        "ev_bn": 15.8,
        "revenue_mn": 52200,
        "ebitda_mn": 3140,
        "ebitda_margin_pct": 6.0,
        "revenue_growth_pct": 2.4,
        "net_debt_mn": 6600,
        "net_debt_ebitda": 2.10,
        "ev_ebitda": 5.0,
        "ev_revenue": 0.30,
        "pe_ntm": 9.8,
        "roe_pct": 8.3,
        "roic_pct": 5.8,
        "current_ratio": 1.08,
        "acq_score": 61,
        "country": "France",
    },
    {
        "name": "Rémy Cointreau",
        "ticker": "RCO.PA",
        "sector": "Luxury & Consumer",
        "mktcap_bn": 3.1,
        "ev_bn": 3.9,
        "revenue_mn": 1118,
        "ebitda_mn": 268,
        "ebitda_margin_pct": 24.0,
        "revenue_growth_pct": -18.2,
        "net_debt_mn": 800,
        "net_debt_ebitda": 2.99,
        "ev_ebitda": 14.6,
        "ev_revenue": 3.49,
        "pe_ntm": 22.4,
        "roe_pct": 12.6,
        "roic_pct": 9.8,
        "current_ratio": 1.55,
        "acq_score": 65,
        "country": "France",
    },
    {
        "name": "Ipsen",
        "ticker": "IPN.PA",
        "sector": "Healthcare & Pharma",
        "mktcap_bn": 7.8,
        "ev_bn": 7.2,
        "revenue_mn": 3300,
        "ebitda_mn": 1155,
        "ebitda_margin_pct": 35.0,
        "revenue_growth_pct": 8.7,
        "net_debt_mn": -600,
        "net_debt_ebitda": -0.52,
        "ev_ebitda": 6.2,
        "ev_revenue": 2.18,
        "pe_ntm": 12.3,
        "roe_pct": 22.1,
        "roic_pct": 17.4,
        "current_ratio": 2.10,
        "acq_score": 82,
        "country": "France",
    },
    {
        "name": "Legrand",
        "ticker": "LR.PA",
        "sector": "Industrials & Engineering",
        "mktcap_bn": 17.6,
        "ev_bn": 19.8,
        "revenue_mn": 8400,
        "ebitda_mn": 2100,
        "ebitda_margin_pct": 25.0,
        "revenue_growth_pct": 3.2,
        "net_debt_mn": 2200,
        "net_debt_ebitda": 1.05,
        "ev_ebitda": 9.4,
        "ev_revenue": 2.36,
        "pe_ntm": 19.8,
        "roe_pct": 19.2,
        "roic_pct": 14.3,
        "current_ratio": 1.62,
        "acq_score": 77,
        "country": "France",
    },
    {
        "name": "bioMérieux",
        "ticker": "BIM.PA",
        "sector": "Healthcare & Pharma",
        "mktcap_bn": 9.4,
        "ev_bn": 9.8,
        "revenue_mn": 3800,
        "ebitda_mn": 912,
        "ebitda_margin_pct": 24.0,
        "revenue_growth_pct": 5.1,
        "net_debt_mn": 400,
        "net_debt_ebitda": 0.44,
        "ev_ebitda": 10.7,
        "ev_revenue": 2.58,
        "pe_ntm": 23.1,
        "roe_pct": 15.7,
        "roic_pct": 12.2,
        "current_ratio": 1.88,
        "acq_score": 79,
        "country": "France",
    },
    {
        "name": "Capgemini",
        "ticker": "CAP.PA",
        "sector": "Technology & Media",
        "mktcap_bn": 20.2,
        "ev_bn": 22.4,
        "revenue_mn": 22100,
        "ebitda_mn": 3094,
        "ebitda_margin_pct": 14.0,
        "revenue_growth_pct": 1.5,
        "net_debt_mn": 2200,
        "net_debt_ebitda": 0.71,
        "ev_ebitda": 7.2,
        "ev_revenue": 1.01,
        "pe_ntm": 14.6,
        "roe_pct": 17.3,
        "roic_pct": 13.1,
        "current_ratio": 1.22,
        "acq_score": 68,
        "country": "France",
    },
    {
        "name": "Pernod Ricard",
        "ticker": "RI.PA",
        "sector": "Luxury & Consumer",
        "mktcap_bn": 24.1,
        "ev_bn": 35.2,
        "revenue_mn": 10832,
        "ebitda_mn": 3249,
        "ebitda_margin_pct": 30.0,
        "revenue_growth_pct": -5.6,
        "net_debt_mn": 11100,
        "net_debt_ebitda": 3.42,
        "ev_ebitda": 10.8,
        "ev_revenue": 3.25,
        "pe_ntm": 14.9,
        "roe_pct": 11.2,
        "roic_pct": 7.8,
        "current_ratio": 1.41,
        "acq_score": 60,
        "country": "France",
    },
    {
        "name": "Carrefour",
        "ticker": "CA.PA",
        "sector": "Retail & Distribution",
        "mktcap_bn": 9.8,
        "ev_bn": 20.4,
        "revenue_mn": 94100,
        "ebitda_mn": 3200,
        "ebitda_margin_pct": 3.4,
        "revenue_growth_pct": 2.1,
        "net_debt_mn": 10600,
        "net_debt_ebitda": 3.31,
        "ev_ebitda": 6.4,
        "ev_revenue": 0.22,
        "pe_ntm": 7.8,
        "roe_pct": 9.1,
        "roic_pct": 5.4,
        "current_ratio": 0.75,
        "acq_score": 44,
        "country": "France",
    },
    {
        "name": "Saint-Gobain",
        "ticker": "SGO.PA",
        "sector": "Industrials & Engineering",
        "mktcap_bn": 22.3,
        "ev_bn": 28.1,
        "revenue_mn": 46600,
        "ebitda_mn": 6060,
        "ebitda_margin_pct": 13.0,
        "revenue_growth_pct": -0.8,
        "net_debt_mn": 5800,
        "net_debt_ebitda": 0.96,
        "ev_ebitda": 4.6,
        "ev_revenue": 0.60,
        "pe_ntm": 9.8,
        "roe_pct": 14.8,
        "roic_pct": 10.2,
        "current_ratio": 1.28,
        "acq_score": 70,
        "country": "France",
    },
    {
        "name": "Vivendi",
        "ticker": "VIV.PA",
        "sector": "Technology & Media",
        "mktcap_bn": 2.8,
        "ev_bn": 4.2,
        "revenue_mn": 9600,
        "ebitda_mn": 960,
        "ebitda_margin_pct": 10.0,
        "revenue_growth_pct": 1.2,
        "net_debt_mn": 1400,
        "net_debt_ebitda": 1.46,
        "ev_ebitda": 4.4,
        "ev_revenue": 0.44,
        "pe_ntm": 11.3,
        "roe_pct": 5.2,
        "roic_pct": 4.8,
        "current_ratio": 1.18,
        "acq_score": 55,
        "country": "France",
    },
]

# ─── HISTORICAL FINANCIALS (5yr IS skeleton per company) ─────────────────────
def get_static_financials(ticker: str) -> dict:
    """Return a 5-year income statement stub for a given ticker."""
    base = {
        "KER.PA": {"revenue": [21212, 20351, 17645, 17026, 15662], "ebitda": [5940, 5296, 4120, 3850, 3500], "ebit": [5020, 4400, 3100, 2800, 2500], "net_income": [3580, 3053, 1826, 1700, 1500]},
        "ATO.PA": {"revenue": [11334, 11373, 10628, 10050, 9800], "ebitda": [980, 720, 413, 350, 310],  "ebit": [320, -200, -1800, -400, 80],   "net_income": [-600, -2900, -3444, -700, -100]},
        "IPN.PA": {"revenue": [2786, 3024, 3296, 3560, 3820], "ebitda": [835, 940, 1048, 1175, 1300],   "ebit": [620, 720, 820, 920, 1040],  "net_income": [460, 560, 680, 780, 900]},
        "LR.PA":  {"revenue": [7561, 7961, 8400, 8720, 9050], "ebitda": [1700, 1890, 2100, 2200, 2310], "ebit": [1280, 1440, 1620, 1700, 1800], "net_income": [900, 1020, 1150, 1200, 1290]},
        "BIM.PA": {"revenue": [3383, 3618, 3800, 3990, 4200], "ebitda": [776, 843, 912, 960, 1050],     "ebit": [520, 580, 640, 680, 750],   "net_income": [370, 420, 470, 510, 570]},
    }
    years = [2020, 2021, 2022, 2023, 2024]
    if ticker in base:
        d = base[ticker]
        return {
            "years": years,
            "revenue": d["revenue"],
            "ebitda": d["ebitda"],
            "ebit": d["ebit"],
            "net_income": d["net_income"],
            "ebitda_margin": [round(e/r*100, 1) for e, r in zip(d["ebitda"], d["revenue"])],
            "ebit_margin":   [round(e/r*100, 1) for e, r in zip(d["ebit"],   d["revenue"])],
        }
    # Generic fallback
    rev = [5000 * (1.03 ** i) for i in range(5)]
    ebitda = [r * 0.14 for r in rev]
    ebit   = [r * 0.09 for r in rev]
    ni     = [r * 0.06 for r in rev]
    return {
        "years": years,
        "revenue":       [round(r) for r in rev],
        "ebitda":        [round(e) for e in ebitda],
        "ebit":          [round(e) for e in ebit],
        "net_income":    [round(n) for n in ni],
        "ebitda_margin": [14.0] * 5,
        "ebit_margin":   [9.0]  * 5,
    }


def get_static_df() -> pd.DataFrame:
    """Return the full static universe as a clean DataFrame."""
    df = pd.DataFrame(STATIC_COMPANIES)
    df = df.rename(columns={
        "name":                "Company",
        "ticker":              "Ticker",
        "sector":              "Sector",
        "mktcap_bn":           "Mkt Cap (€bn)",
        "ev_bn":               "EV (€bn)",
        "revenue_mn":          "Revenue (€mn)",
        "ebitda_mn":           "EBITDA (€mn)",
        "ebitda_margin_pct":   "EBITDA Margin %",
        "revenue_growth_pct":  "Rev Growth %",
        "net_debt_mn":         "Net Debt (€mn)",
        "net_debt_ebitda":     "ND/EBITDA",
        "ev_ebitda":           "EV/EBITDA",
        "ev_revenue":          "EV/Revenue",
        "pe_ntm":              "NTM P/E",
        "roe_pct":             "ROE %",
        "roic_pct":            "ROIC %",
        "current_ratio":       "Current Ratio",
        "acq_score":           "Score",
        "country":             "Country",
    })
    return df
